// Generated by gencpp from file detector_msgs/BBoxArray.msg
// DO NOT EDIT!


#ifndef DETECTOR_MSGS_MESSAGE_BBOXARRAY_H
#define DETECTOR_MSGS_MESSAGE_BBOXARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <detector_msgs/BBox.h>

namespace detector_msgs
{
template <class ContainerAllocator>
struct BBoxArray_
{
  typedef BBoxArray_<ContainerAllocator> Type;

  BBoxArray_()
    : header()
    , bboxes()  {
    }
  BBoxArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bboxes(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::detector_msgs::BBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::detector_msgs::BBox_<ContainerAllocator> >::other >  _bboxes_type;
  _bboxes_type bboxes;





  typedef boost::shared_ptr< ::detector_msgs::BBoxArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_msgs::BBoxArray_<ContainerAllocator> const> ConstPtr;

}; // struct BBoxArray_

typedef ::detector_msgs::BBoxArray_<std::allocator<void> > BBoxArray;

typedef boost::shared_ptr< ::detector_msgs::BBoxArray > BBoxArrayPtr;
typedef boost::shared_ptr< ::detector_msgs::BBoxArray const> BBoxArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_msgs::BBoxArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_msgs::BBoxArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_msgs::BBoxArray_<ContainerAllocator1> & lhs, const ::detector_msgs::BBoxArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.bboxes == rhs.bboxes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_msgs::BBoxArray_<ContainerAllocator1> & lhs, const ::detector_msgs::BBoxArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_msgs::BBoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_msgs::BBoxArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_msgs::BBoxArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_msgs::BBoxArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_msgs::BBoxArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_msgs::BBoxArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_msgs::BBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ed748f248b539ee6ad03e80ae91120d";
  }

  static const char* value(const ::detector_msgs::BBoxArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ed748f248b539eeULL;
  static const uint64_t static_value2 = 0x6ad03e80ae91120dULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_msgs::BBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_msgs/BBoxArray";
  }

  static const char* value(const ::detector_msgs::BBoxArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_msgs::BBoxArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"detector_msgs/BBox[] bboxes\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: detector_msgs/BBox\n"
"string label\n"
"float64 score\n"
"int64 x\n"
"int64 y\n"
"int64 w\n"
"int64 h\n"
;
  }

  static const char* value(const ::detector_msgs::BBoxArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_msgs::BBoxArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bboxes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBoxArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_msgs::BBoxArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_msgs::BBoxArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bboxes[]" << std::endl;
    for (size_t i = 0; i < v.bboxes.size(); ++i)
    {
      s << indent << "  bboxes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::detector_msgs::BBox_<ContainerAllocator> >::stream(s, indent + "    ", v.bboxes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_MSGS_MESSAGE_BBOXARRAY_H
