// Generated by gencpp from file detector_msgs/SetTransformFromBBoxResponse.msg
// DO NOT EDIT!


#ifndef DETECTOR_MSGS_MESSAGE_SETTRANSFORMFROMBBOXRESPONSE_H
#define DETECTOR_MSGS_MESSAGE_SETTRANSFORMFROMBBOXRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detector_msgs
{
template <class ContainerAllocator>
struct SetTransformFromBBoxResponse_
{
  typedef SetTransformFromBBoxResponse_<ContainerAllocator> Type;

  SetTransformFromBBoxResponse_()
    : result(false)  {
    }
  SetTransformFromBBoxResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetTransformFromBBoxResponse_

typedef ::detector_msgs::SetTransformFromBBoxResponse_<std::allocator<void> > SetTransformFromBBoxResponse;

typedef boost::shared_ptr< ::detector_msgs::SetTransformFromBBoxResponse > SetTransformFromBBoxResponsePtr;
typedef boost::shared_ptr< ::detector_msgs::SetTransformFromBBoxResponse const> SetTransformFromBBoxResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator1> & lhs, const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator1> & lhs, const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detector_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detector_msgs/SetTransformFromBBoxResponse";
  }

  static const char* value(const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
;
  }

  static const char* value(const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTransformFromBBoxResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detector_msgs::SetTransformFromBBoxResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTOR_MSGS_MESSAGE_SETTRANSFORMFROMBBOXRESPONSE_H
