// Generated by gencpp from file detector_msgs/AddTransformToManager.msg
// DO NOT EDIT!


#ifndef DETECTOR_MSGS_MESSAGE_ADDTRANSFORMTOMANAGER_H
#define DETECTOR_MSGS_MESSAGE_ADDTRANSFORMTOMANAGER_H

#include <ros/service_traits.h>


#include <detector_msgs/AddTransformToManagerRequest.h>
#include <detector_msgs/AddTransformToManagerResponse.h>


namespace detector_msgs
{

struct AddTransformToManager
{

typedef AddTransformToManagerRequest Request;
typedef AddTransformToManagerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTransformToManager
} // namespace detector_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detector_msgs::AddTransformToManager > {
  static const char* value()
  {
    return "bf7912ca51f884d0a3b0d663503f42cd";
  }

  static const char* value(const ::detector_msgs::AddTransformToManager&) { return value(); }
};

template<>
struct DataType< ::detector_msgs::AddTransformToManager > {
  static const char* value()
  {
    return "detector_msgs/AddTransformToManager";
  }

  static const char* value(const ::detector_msgs::AddTransformToManager&) { return value(); }
};


// service_traits::MD5Sum< ::detector_msgs::AddTransformToManagerRequest> should match
// service_traits::MD5Sum< ::detector_msgs::AddTransformToManager >
template<>
struct MD5Sum< ::detector_msgs::AddTransformToManagerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detector_msgs::AddTransformToManager >::value();
  }
  static const char* value(const ::detector_msgs::AddTransformToManagerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detector_msgs::AddTransformToManagerRequest> should match
// service_traits::DataType< ::detector_msgs::AddTransformToManager >
template<>
struct DataType< ::detector_msgs::AddTransformToManagerRequest>
{
  static const char* value()
  {
    return DataType< ::detector_msgs::AddTransformToManager >::value();
  }
  static const char* value(const ::detector_msgs::AddTransformToManagerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detector_msgs::AddTransformToManagerResponse> should match
// service_traits::MD5Sum< ::detector_msgs::AddTransformToManager >
template<>
struct MD5Sum< ::detector_msgs::AddTransformToManagerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detector_msgs::AddTransformToManager >::value();
  }
  static const char* value(const ::detector_msgs::AddTransformToManagerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detector_msgs::AddTransformToManagerResponse> should match
// service_traits::DataType< ::detector_msgs::AddTransformToManager >
template<>
struct DataType< ::detector_msgs::AddTransformToManagerResponse>
{
  static const char* value()
  {
    return DataType< ::detector_msgs::AddTransformToManager >::value();
  }
  static const char* value(const ::detector_msgs::AddTransformToManagerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECTOR_MSGS_MESSAGE_ADDTRANSFORMTOMANAGER_H
