(cl:defpackage detector_msgs-srv
  (:use )
  (:export
   "ADDTRANSFORMTOMANAGER"
   "<ADDTRANSFORMTOMANAGER-REQUEST>"
   "ADDTRANSFORMTOMANAGER-REQUEST"
   "<ADDTRANSFORMTOMANAGER-RESPONSE>"
   "ADDTRANSFORMTOMANAGER-RESPONSE"
   "GETOBJECTDETECTION"
   "<GETOBJECTDETECTION-REQUEST>"
   "GETOBJECTDETECTION-REQUEST"
   "<GETOBJECTDETECTION-RESPONSE>"
   "GETOBJECTDETECTION-RESPONSE"
   "SETTRANSFORMFROMBBOX"
   "<SETTRANSFORMFROMBBOX-REQUEST>"
   "SETTRANSFORMFROMBBOX-REQUEST"
   "<SETTRANSFORMFROMBBOX-RESPONSE>"
   "SETTRANSFORMFROMBBOX-RESPONSE"
  ))

